#!/bin/sh

dbName=../$1
shift 1

cd ./tools
echo `pwd`
echo $dbName

if [ -f "$dbName" ] 
    then java -jar schemaSpy_5.0.0.jar -u atronah -t sqlite -db "$dbName" -o ../doc
else echo no file $dbName
fi



